### ISSUE TITLE
Can't run a build with paper-tags installed

### ISSUE THREAD

**Issue by ongubsy** [PolymerEl/paper-tags#17]
polymer build with  paper-tags version 1.4.0 results in:

```
info:    Preparing build...
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to optimize .js file C:\Users\Usuario\polymer\bower_components\paper-tags\paper-tags-input.html_script_0.js
{ err:
   { message: 'SyntaxError: Unexpected token name «of», expected punc «;»',
     filename: 0,
     line: 114,
     col: 19,
     pos: 2413,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (C:\\Users\\Usuario\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (C:\\Users\\Usuario\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1555:11)\n    at croak (eval at <anonymous> (C:\\Users\\Usuario\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2094:9)\n    at token_error (eval at <anonymous> (C:\\Users\\Usuario\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2102:9)\n    at expect_token (eval at <anonymous> (C:\\Users\\Usuario\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2115:9)\n    at expect (eval at <anonymous> (C:\\Users\\Usuario\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2118:36)\n    at regular_for (eval at <anonymous> (C:\\Users\\Usuario\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2359:9)\n    at for_ (eval at <anonymous> (C:\\Users\\Usuario\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2355:16)\n    at eval (eval at <anonymous> (C:\\Users\\Usuario\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2234:24)\n    at eval (eval at <anonymous> (C:\\Users\\Usuario\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2141:24)' } }


```

**Comment by christophe-g** [comment]
Hey, Thanks for the report, 
What is the version of you polymer-cli ?
C.

**Comment by christophe-g** [comment]
Can you  tell me if you are still seeing the issue with v1.4.1 ? 
C.

**Comment by ongubsy** [comment]
Hello,

```
polymer --version
0.17.0
```

I'll try with the minor build of paper-tags that you mentioned later on, and post the results.

**Comment by ongubsy** [comment]
Version 1.4.1 of paper-tags solved the issue, thanks.
